CREATE TABLE SOLDIER
( SOLDIER_NO VARCHAR2(10) PRIMARY KEY
, name VARCHAR2(20)
, JOIN_date DATE
, SVC_LENGTH  VARCHAR2(25)
, AGE VARCHAR2(20)
, email      VARCHAR2(25) 
, CELL_nO   VARCHAR2(10)  

) ;

CREATE TABLE IPFT_INFO
(
BIANNUAL  VARCHAR2(10)
,BIANNUAL_DATE DATE

,constraint BI_DATE_PK PRIMARY
KEY(BIANNUAL_DATE)

);

CREATE TABLE ITEM_INFO(
ITEM_ID  VARCHAR2(10),
ITEM_NAME VARCHAR2(10),
constraint ITEM_ID_fk FOREIGN KEY(ITEM_ID) references FAILED_PER_ITEM(ITEM_ID)
);
	
	
	
CREATE TABLE FAILED_PER_ITEM
(
SOLDIER_NO  VARCHAR2(10)
,ITEM_ID VARCHAR2(10)
, BIANNUAL_DATE DATE
,constraint SOLDIER_NO_fk FOREIGN
KEY(SOLDIER_NO) references SOLDIER(SOLDIER_NO)
,constraint BI_DATE_fk FOREIGN
KEY(BIANNUAL_DATE) references IPFT_INFO(BIANNUAL_DATE)

) ;

	
	
	
CREATE TABLE OFFICER
(BA_NO VARCHAR2(20),
NAME VARCHAR2(20),
D DATE,
RANK VARCHAR2(20),
constraint BA_NO_PK PRIMARY KEY(BA_NO) ) ;
	
	
CREATE TABLE OIC
(BIANNUAL_DATE DATE,
BA_NO VARCHAR2(20),
constraint OIC_DATE_fk FOREIGN KEY(BIANNUAL_DATE) references IPFT_INFO(BIANNUAL_DATE),
constraint BA_NO_fk FOREIGN KEY(BA_NO) references OFFICER(BA_NO)
);
	
	
CREATE table TOTAL_RESULT(
SOLDIER_NO VARCHAR2(20),
BIANNUAL_DATE DATE,
RESULT VARCHAR2(20)
);	
	

alter table item_info
add constraint item_id_fk
foreign key(item_id) references failed_per_item(item_id)

alter table TOTAL_RESULT
add constraint DATE_FK
foreign key(BIANNUAL_DATE) references IPFT_INFO(BIANNUAL_DATE)
	
	
CREATE table BENCHMARK (
    SEX	        VARCHAR2(10),
    UPPER_AGE 	VARCHAR2(10),
    LOWER_AGE 	VARCHAR2(10),
    A1.6KM 	VARCHAR2(10),
    BEAM	VARCHAR2(10),
    PUSH_UP	VARCHAR2(10),
    A3.2KM	VARCHAR2(10),
    HORIZONTAL_ROPE	VARCHAR2(10),
    A6FT_WALL 	VARCHAR2(10),
    SWIMMING	VARCHAR2(10),
    REACH_UP	VARCHAR2(10),
    SIT_UP	VARCHAR2(10)
)